# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighted_cov <- function(x, w) {
    .Call(`_independentsubclustering_weighted_cov`, x, w)
}

weighted_reg_beta <- function(X, wt, Y) {
    .Call(`_independentsubclustering_weighted_reg_beta`, X, wt, Y)
}

arma_direct2 <- function(X, w, y) {
    .Call(`_independentsubclustering_arma_direct2`, X, w, y)
}

update_bars_sigma_inv <- function(G, setx, sety, Sg, Sgh, B, psi, px, py, p) {
    .Call(`_independentsubclustering_update_bars_sigma_inv`, G, setx, sety, Sg, Sgh, B, psi, px, py, p)
}

m_step_gamma <- function(G, sigma_bar_g_h_inv, mu_bar_g_h, wt, data, Gamma, max_update = 10L, epsilon = 1e-8) {
    .Call(`_independentsubclustering_m_step_gamma`, G, sigma_bar_g_h_inv, mu_bar_g_h, wt, data, Gamma, max_update, epsilon)
}

m_step_gamma_tr <- function(G, sigma_bar_g_h_inv, mu_bar_g_h, wt, data, Gamma, max_update = 10L, epsilon = 1e-8) {
    .Call(`_independentsubclustering_m_step_gamma_tr`, G, sigma_bar_g_h_inv, mu_bar_g_h, wt, data, Gamma, max_update, epsilon)
}

m_step_gamma_dual <- function(G, sigma_bar_g_h_inv, mu_bar_g_h, wt, data, Gamma, max_update = 10L, epsilon = 1e-8) {
    .Call(`_independentsubclustering_m_step_gamma_dual`, G, sigma_bar_g_h_inv, mu_bar_g_h, wt, data, Gamma, max_update, epsilon)
}

mixlogden_helper <- function(px, py, G, sigma_bar_g_h_inv, mu_bar_g_h, tau_g_h, rotX, rotY) {
    .Call(`_independentsubclustering_mixlogden_helper`, px, py, G, sigma_bar_g_h_inv, mu_bar_g_h, tau_g_h, rotX, rotY)
}

logden_helper <- function(G, sigma_bar_g_h_inv, mu_bar_g_h, tau_g_h, rotX, rotY, rotZ, data) {
    .Call(`_independentsubclustering_logden_helper`, G, sigma_bar_g_h_inv, mu_bar_g_h, tau_g_h, rotX, rotY, rotZ, data)
}

logden_wts <- function(z) {
    .Call(`_independentsubclustering_logden_wts`, z)
}

logden_loglik <- function(z) {
    .Call(`_independentsubclustering_logden_loglik`, z)
}

m_step_primary <- function(z_ngh, setx, Gx, X, diagonal = FALSE) {
    .Call(`_independentsubclustering_m_step_primary`, z_ngh, setx, Gx, X, diagonal)
}

m_step_secondary <- function(z_ngh, sety, Gy, X, Y, regression, subcluster, diagonal = FALSE) {
    .Call(`_independentsubclustering_m_step_secondary`, z_ngh, sety, Gy, X, Y, regression, subcluster, diagonal)
}

e_step_helper <- function(px, py, G, sigma_bar_g_h_inv, mu_bar_g_h, tau_g_h, rotX, rotY) {
    .Call(`_independentsubclustering_e_step_helper`, px, py, G, sigma_bar_g_h_inv, mu_bar_g_h, tau_g_h, rotX, rotY)
}

continue_em <- function(state, niter, hold_z = FALSE, progress = TRUE, loglik = TRUE, diagonal = FALSE, gamma_updates = 100L, gamma_epsilon = 1e-8, loglik_eps = 1e-4) {
    .Call(`_independentsubclustering_continue_em`, state, niter, hold_z, progress, loglik, diagonal, gamma_updates, gamma_epsilon, loglik_eps)
}

